name: Deploy Worker
on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Setup rust
        run: apt install rustup
      - uses: actions/checkout@v6
      - name: Build crate
        working-directory: ./squaregb
        run: ./build.sh
      - name: NPM Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy 
