name: Playwright Tests
on:
  push:
    branches: [ ci-updates, main  ]
jobs:
  build:
    uses: ./.github/workflows/build.yml
  playwright:
    name: 'Playwright Tests'
    needs: build
    timeout-minutes: 60
    runs-on: ubuntu-24.04
    container:
      image: mcr.microsoft.com/playwright:v1.59.1-noble
      options: --user 1001
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v6
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    # - name: Install Playwright Browsers
    #   run: npx playwright install --with-deps
    - name: Pull down wasm build
      uses: actions/download-artifact@v8
      with: 
        name: 'wasm_dist'
        path: './squaregb/dist'
    - name: Show playwright browsers
      run: npx playwright install --list
    - name: Run Playwright tests
      run: npx playwright test
    # - name: Upload black boot rom png
    #   uses: actions/upload-artifact@v7
    #   if: always()
    #   with:
    #     name: 'boot_black_image'
    #     path: './boot_black_screen.png'

